---
- hosts: K8S-Server
  become: yes
  roles:
    - role: system
      tags: system
    - role: docker
      tags: docker
        #    - role: "{{ gui_type }}"
        #      tags: gui
        #      when: gui == "yes" 
...
