---
- hosts: K8S-Server
  become: yes
  roles:
    - role: system
      tags: system
    - role: virtualbox
      tags: virtualbox
    - role: k8s
      tags: k8s
    - role: docker
      tags: docker
...
