---
- name: iptables uninstalled. Conflict with iptables-nft
  pacman:
    name: iptables
    state: absent
    force: yes

- name: Install pip3 on K8S-Master. It is needed for building the docker image
  pacman:
    name: 
      - python-pip
      - python-docker
    state: present
  when: hostname == "K8S-Master"

- name: Install K8S packages using yay
  kewlfft.aur.aur:
    use: yay
    name:
      - kubelet
      - kubeadm
      - kubectl when: hostname == "K8S-Master"

- name: Install packages with pacman ansible module
  pacman:
    name:
      - ethtool
      - socat
      - conntrack-tools
    state: present
    
### Install HAProxy
- name: Create /etc/haproxy directory on K8S-Master
  file:
    path: /etc/haproxy
    state: directory
    mode: '0755'
  when: hostname == "K8S-Master"

- name: Copy HAProxy configuration to K8S master node
  template:
    src: ./templates/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: '0644'
  when: hostname == "K8S-Master"

- name: Create directory for Dockerfile
  file:
    path: /root/Dockerfile
    state: directory
    mode: '0755'
  when: hostname == "K8S-Master"

- name: Copy HAProxy configuration to K8S master node
  copy:
    src: files/Dockerfile
    dest: /root/Dockerfile
    owner: root
    group: root
    mode: '0600'
  when: hostname == "K8S-Master"

- name: Build docker image from Dockerfile
  docker_image:
    name: "{{ docker_image_name }}"
    build:
      pull: yes
      path: "{{ docker_file_folder }}"
    state: present
    source: build
  when: hostname == "K8S-Master"

- name: Create docker container
  docker_container:
    name: "{{ docker_container_name }}"
    image: "{{ docker_image_name }}"
    restart_policy: always
    published_ports:
      - 6442:6443
      - 8404:8404
    mounts:
      - source: /etc/haproxy
        target: /usr/local/etc/haproxy
        type: bind
        read_only: yes
    state: started
  when: hostname == "K8S-Master"

- name: Enable systemd-timesyncd.service
  systemd:
    name: kubelet.service
    state: started
    enabled: yes
...
