---
- name: Install K8S packages using yay
  become: yes
  kewlfft.aur.aur:
    use: yay
    name:
      - kubelet
      - kubeadm

- name: Install packages with pacman ansible module
  pacman:
    name:
      - ethtool
      - ebtables
      - socat
      - conntrack-tools
    state: present
...
