---
K8S-Master-IP: '192.168.2.200'
K8S-Node01-IP: '192.168.2.201'
K8S-Node02-IP: '192.168.2.202'
Nodes:
  - K8S-Node01-IP
  - K8S-Node02-IP

my_user: 'sinotna'
my_group: 'sinotna'
my_home: '/home/{{ my_user }}'
virtualbox: "yes"
...
