---
K8S_Master_IP: '192.168.2.200'
K8S_Node01_IP: '192.168.2.201'
K8S_Node02_IP: '192.168.2.202'
Nodes:
  - K8S-Node01_
  - K8S-Node02_

my_user: 'sinotna'
my_group: 'sinotna'
my_home: '/home/{{ my_user }}'
repos_path: '/home/{{ my_user }}'
virtualbox: "yes"

### Docker HAPROXY
docker_file_folder: "/root/Dockerfile"
docker_image_name: "haproxy"
docker_container_name: "k8s_haproxy"
haproxy_stats_port: "8404"
k8s_port: "6443"
...
