---
- name: Set a hostname
  hostname:
    name: "{{ hostname }}"

- name: Set NTP servers in /etc/systemd/timesyncd.conf
  replace:
    path: /etc/systemd/timesyncd.conf
    regexp: '#NTP='
    replace: 'NTP=0.gr.pool.ntp.org 1.gr.pool.ntp.org 2.gr.pool.ntp.org'
  tags: ntp

- name: Enable systemd-timesyncd.service   
  systemd:
    name: systemd-timesyncd.service
    state: started
    enabled: yes
  tags: ntp
...
