---
- name: Set a hostname
  hostname:
    name: "{{ hostname }}"

- name: Set NTP servers in /etc/systemd/timesyncd.conf
  replace:
    path: /etc/systemd/timesyncd.conf
    regexp: '#NTP='
    replace: 'NTP=0.gr.pool.ntp.org 1.gr.pool.ntp.org 2.gr.pool.ntp.org'
  tags: ntp

- name: Enable systemd-timesyncd.service   
  systemd:
    name: systemd-timesyncd.service
    state: started
    enabled: yes
  tags: ntp

- name: Install packages with pacman ansible module
  pacman:
    name:
      - sudo
      - base-devel
      - binutils
      - vim
      - tree
      - gnu-netcat
    state: present

- name: Check if YAY is installed
  shell: "pacman -Q |grep yay"
  register: YAY_installation_status
  check_mode: no
  ignore_errors: yes
  changed_when: False

- name: YAY repo sync
  git:
    repo: https://aur.archlinux.org/yay-git.git
    dest: "{{ repos_path }}/YAY"
    update: yes
  when:  "YAY_installation_status.rc  == 1"

- name: YAY directory ownership
  file:
    path: "{{ repos_path }}/YAY"
    owner: "{{ my_user }}"
    group: "{{ my_user }}"
    recurse: yes
  when:  "YAY_installation_status.rc  == 1"

- name: Install YAY
  shell: |
    cd "{{ repos_path }}/YAY"
    makepkg -fsi --noconfirm
  when:  "YAY_installation_status.rc  == 1"
  become: yes
  become_user: "{{ my_user }}"

- name: Replace ccache in makepkg.conf
  replace:
    path: /etc/makepkg.conf
    regexp: '!ccache'
    replace: 'ccache'

- name: Replace MAKEFLAGS in makepkg
  replace:
    path: /etc/makepkg.conf
    regexp: '#MAKEFLAGS="-j2"'
    replace: 'MAKEFLAGS="-j{{ansible_processor_vcpus}}"'
    
- name: Create /etc/haproxy directory on K8S-Master
  file:
    path: /etc/haproxy
    state: directory
    mode: '0755'

- name: Copy HAProxy configuration to K8S master node
  template:
    src: ./templates/haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
    mode: '0644'
  when: hostnamee == "K8S-Master"
...
