---
- name: Check if YAY is installed
  shell: "pacman -Q |grep yay"
  register: YAY_installation_status
  check_mode: no
  ignore_errors: yes
  changed_when: False
  tags: YAY_repo

- name: YAY repo sync
  git:
    repo: https://aur.archlinux.org/yay.git
    dest: "{{ repos_path }}/YAY"
    update: yes
  when:  "YAY_installation_status.rc  == 1"
  tags: YAY_repo

- name: YAY directory ownership
  file:
    path: "{{ repos_path }}/YAY"
    owner: "{{ my_user }}"
    group: "{{ my_user }}"
    recurse: yes
  when:  "YAY_installation_status.rc  == 1"
  tags: YAY_repo

- name: Install YAY
  shell: |
    cd "{{ repos_path }}/YAY"
    makepkg -fsi --noconfirm
  when:  "YAY_installation_status.rc  == 1"
  become: yes
  become_user: "{{ my_user }}"

- name: Replace ccache in makepkg.conf
  replace: 
    path: /etc/makepkg.conf
    regexp: '!ccache'
    replace: 'ccache'

- name: Replace MAKEFLAGS in makepkg
  replace: 
    path: /etc/makepkg.conf
    regexp: '#MAKEFLAGS="-j2"'
    replace: 'MAKEFLAGS="-j{{ansible_processor_vcpus}}"'
  tags: test

- name: Install packages from AUR
  aur:
    use: yay
    name:
      - google-chrome
      - cylon
      - visual-studio-code-bin
      - nerd-fonts-hack
      #      - snapd
      - skypeforlinux-stable-bin
      - megasync
      #      - spotify
      - antigen-git
      #      - spotify
      #      - stremio-beta
      - viber
      - pyenv-virtualenv
  become: yes
  become_user: "{{ my_user }}"  
  tags: aur_packages

- name: Check if oh-my-zsh is installed
  stat:
    path: /home/{{ my_user }}/.oh-my-zsh
  register: oh_my_zsh
  tags: zsh

- name: Install oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  become: yes
  become_user: "{{ my_user }}"  
  when: oh_my_zsh.stat.exists == False 
  tags: zsh

- name: Change shell for "{{ my_user }}"
  user:
    name: "{{ my_user }}"
    shell: /bin/zsh
  tags: zsh

#### Powerlevel10k
#https://github.com/romkatv/powerlevel10k#meslo-nerd-font-patched-for-powerlevel10k
- name: MesloLGS NF fonts installation.
  get_url:
    url: "{{ item }}"
    dest: /usr/share/fonts/TTF
    mode: '0644'
  with_items:
     - "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf"
     - "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf"
     - "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf"
     - "https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf"
  tags: powerlevel10k

- name: Update the fontconfig font cache
  command: fc-cache
  ignore_errors: yes
  changed_when: False
  
- name: Powerlevel10k installation
  git:
    repo: 'https://github.com/romkatv/powerlevel10k.git'
    dest: /home/{{ my_user }}/.oh-my-zsh/themes/powerlevel10k
    clone: yes
    depth: 1
    update: yes
  become: yes
  become_user: "{{ my_user }}"  
  tags: powerlevel10k

- name: Copy p10k.zsh
  copy:
    src: ./files/p10k.zsh
    dest: /home/{{ my_user }}/.p10k.zsh
    owner: "{{ my_user }}"
    group: "{{ my_group }}"
    mode: '0644'
  tags: powerlevel10k

#################################################################################################

- name: Copy antigenrc
  template:
    src: ./files/antigenrc
    dest: /home/{{ my_user }}/.antigenrc
    owner: "{{ my_user }}"
    group: "{{ my_group }}"
    mode: '0644'
  tags: zsh

- name: Copy .zshrc
  template:
    src: ./templates/zshrc.j2
    dest: /home/{{ my_user }}/.zshrc
    owner: "{{ my_user }}"
    group: "{{ my_group }}"
    mode: '0644'
  tags: zsh

- name: Copy .zshrc_backup
  copy:
    src: ./files/zshrc_backup
    dest: /home/{{ my_user }}/.zshrc_backup
    owner: "{{ my_user }}"
    group: "{{ my_group }}"
    mode: '0644'
  tags: zsh

- name: create zshrc_files directory
  file:
    path: /home/{{ my_user }}/.zshrc_files
    owner: "{{ my_user }}"
    state: directory
    group: "{{ my_group }}"
    mode: '0755'
  tags: zsh

- name: Copy az.completion
  copy:
    src: ./files/az.completion
    dest: /home/{{ my_user }}/.zshrc_files/
    owner: "{{ my_user }}"
    group: "{{ my_group }}"
    mode: '0644'
  tags: zsh
...
