---
- name: create swap volume
  lvg:
    vg: swap_vg
    pvs: "{{ swap_disk }}"
  when: ansible_devices.sdb.size == "8.00 GB"

- name: create home volume
  lvg:
    vg: home_vg
    pvs: "{{ home_disk }}"
  when: ansible_devices.sdc.size == "50.00 GB"
 
- name: Create swap logical volume
  lvol:
    vg: "{{ vg_swap }}"
    lv: "{{ lv_swap }}"
    size: +100%FREE

- name: Create home logical volume 
  lvol:
    vg: "{{ vg_home }}"
    lv: "{{ lv_home }}"
    size: +100%FREE

- name: Create a ext4 filesystem on lv_home
  filesystem:
    fstype: ext4
    dev: /dev/{{ vg_home }}/{{ lv_home }}

- name: Create swap disk
  command: mkswap /dev/{{ vg_swap }}/{{ lv_swap }}
  when: ansible_memory_mb.swap.free != 8187
  tags: swap
    
- name: Register home uuid
  shell: "blkid -s UUID -o value /dev/{{ vg_home }}/{{ lv_home }}" 
  register: uuid_home
  changed_when: False
  tags: uuid

- name: Register swap uuid
  shell: "blkid -s UUID -o value /dev/{{ vg_swap }}/{{ lv_swap }}" 
  register: uuid_swap
  changed_when: False
  tags: uuid

- name: Add new swap in fstab
  lineinfile:
    path: /etc/fstab
    regexp: 'swap'
    line: UUID={{ uuid_swap.stdout }}      none    swap    defaults        0 0
  tags: "fstab_swap"

- name: Add new home in fstab
  lineinfile:
    path: /etc/fstab
    regexp: 'home'
    line: UUID={{ uuid_home.stdout }}      /home    ext4    defaults        0 1
  tags: "fstab_home"

- name: Mount new disks
  shell: mount -a
  args:
    warn: false # set warn=false to prevent warning`
  changed_when: False
...
