---
- name: Install packages with pacman command
  command: pacman -S plasma-desktop --noconfirm 
  changed_when: False

- name: Install packages with pacman ansible module
  pacman:
    name:
      - sddm
      - enlightenment
      - terminology 
      - connman
    state: present
  notify: enable_start_sddm

- name: sddm enabled to autostart
  systemd:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - sddm
    - connman

- name: Install packages from AUR
  aur:
    use: yay
    name:
      - econnman
  become: yes
  become_user: "{{ my_user }}"  
...
